name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: npm i 
    - run: apt install -y chromium
    
