name: CI

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install requests bs4 openpyxl
    - run: mkdir urls
    - run: python main.py
    - run: |
        mkdir -p books
        cat book_targs | while read tag; do
          python main.py $tag
          git config --global user.email "shinhwagk@outlook.com"
          git config --global user.name "shinhwagk"
          git add books
          git commit -m "test"
          git push
        done
